on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.arrudabaga.com
        local-dir: ./http/
        server-dir: /domains/arrudabaga.com/public_html/
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
